---
# DecentralBet Infrastructure Inventory
all:
  children:
    azure:
      children:
        aks_cluster:
          hosts:
            aks-node-1:
              ansible_host: "{{ aks_node_1_ip | default('10.0.1.4') }}"
              ansible_user: azureuser
              node_role: master
            aks-node-2:
              ansible_host: "{{ aks_node_2_ip | default('10.0.1.5') }}"
              ansible_user: azureuser
              node_role: worker
            aks-node-3:
              ansible_host: "{{ aks_node_3_ip | default('10.0.1.6') }}"
              ansible_user: azureuser
              node_role: worker
          vars:
            kubernetes_version: "1.28.5"
            cluster_name: "decentralbet-aks"
            
        databases:
          hosts:
            cosmosdb:
              ansible_host: "{{ cosmosdb_endpoint }}"
              db_type: mongodb
              connection_string: "{{ cosmosdb_connection_string }}"
            redis:
              ansible_host: "{{ redis_endpoint }}"
              port: 6380
              ssl_enabled: true
              
        load_balancers:
          hosts:
            application_gateway:
              ansible_host: "{{ app_gateway_ip }}"
              gateway_type: azure_application_gateway
              ssl_enabled: true
              
    monitoring:
      hosts:
        prometheus:
          ansible_host: "{{ prometheus_endpoint }}"
          metrics_port: 9090
        grafana:
          ansible_host: "{{ grafana_endpoint }}"
          dashboard_port: 3000
          
  vars:
    # Azure Configuration
    azure_subscription_id: "{{ vault_azure_subscription_id }}"
    azure_resource_group: "rg-aks-final"
    azure_location: "East US"
    
    # Application Configuration  
    app_name: decentralbet
    environment: "{{ env | default('production') }}"
    namespace: decentralbet
    
    # Container Registry
    acr_name: "{{ vault_acr_name }}"
    acr_login_server: "{{ vault_acr_login_server }}"
    
    # Security
    enable_rbac: true
    enable_network_policies: true
    enable_pod_security_policies: true
    
    # Monitoring
    enable_monitoring: true
    metrics_retention_days: 30
    
    # Auto-scaling
    enable_hpa: true
    min_replicas: 2
    max_replicas: 10
    cpu_threshold: 70
    memory_threshold: 80
