apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: decentralbet
  labels:
    app: frontend
    component: web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
        component: web
    spec:
      containers:
      - name: frontend
        image: decentralbetacr.azurecr.io/decentralbet-frontend:latest
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: decentralbet-config
        env:
        - name: NEXT_PUBLIC_API_URL
          value: "https://decentralbet.azurewebsites.net/api/v1"
        - name: NEXT_PUBLIC_WS_URL
          value: "wss://decentralbet.azurewebsites.net"
        - name: NEXT_PUBLIC_CHAIN_ID
          value: "11155111"  # Sepolia testnet
        - name: NEXT_PUBLIC_ETHEREUM_RPC_URL
          valueFrom:
            secretKeyRef:
              name: decentralbet-secrets
              key: ETHEREUM_RPC_URL
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 300m
            memory: 256Mi
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 3
        securityContext:
          runAsNonRoot: true
          runAsUser: 1001
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          capabilities:
            drop:
            - ALL
      restartPolicy: Always
      securityContext:
        fsGroup: 1001
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: decentralbet
  labels:
    app: frontend
spec:
  selector:
    app: frontend
  ports:
  - name: http
    port: 3000
    targetPort: 3000
    protocol: TCP
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: frontend-hpa
  namespace: decentralbet
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: frontend
  minReplicas: 2
  maxReplicas: 6
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
