---
# Service Account for DecentralBet Application
apiVersion: v1
kind: ServiceAccount
metadata:
  name: decentralbet-sa
  namespace: decentralbet
  labels:
    app: decentralbet
    component: security
automountServiceAccountToken: true

---
# Role for application-specific permissions
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: decentralbet-app-role
  namespace: decentralbet
rules:
- apiGroups: [""]
  resources: ["pods", "services", "configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get", "list"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["metrics.k8s.io"]
  resources: ["pods", "nodes"]
  verbs: ["get", "list"]

---
# RoleBinding to associate ServiceAccount with Role
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: decentralbet-app-rolebinding
  namespace: decentralbet
subjects:
- kind: ServiceAccount
  name: decentralbet-sa
  namespace: decentralbet
roleRef:
  kind: Role
  name: decentralbet-app-role
  apiGroup: rbac.authorization.k8s.io

---
# ClusterRole for monitoring and metrics access
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: decentralbet-monitoring-role
rules:
- apiGroups: [""]
  resources: ["nodes", "nodes/metrics", "services", "endpoints", "pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["extensions"]
  resources: ["ingresses"]
  verbs: ["get", "list", "watch"]

---
# ClusterRoleBinding for monitoring
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: decentralbet-monitoring-rolebinding
subjects:
- kind: ServiceAccount
  name: decentralbet-sa
  namespace: decentralbet
roleRef:
  kind: ClusterRole
  name: decentralbet-monitoring-role
  apiGroup: rbac.authorization.k8s.io

---
# Pod Security Policy (if supported by cluster)
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: decentralbet-psp
  namespace: decentralbet
spec:
  privileged: false
  allowPrivilegeEscalation: false
  requiredDropCapabilities:
    - ALL
  volumes:
    - 'configMap'
    - 'emptyDir'
    - 'projected'
    - 'secret'
    - 'downwardAPI'
    - 'persistentVolumeClaim'
  hostNetwork: false
  hostIPC: false
  hostPID: false
  runAsUser:
    rule: 'MustRunAsNonRoot'
  supplementalGroups:
    rule: 'MustRunAs'
    ranges:
      - min: 1
        max: 65535
  fsGroup:
    rule: 'MustRunAs'
    ranges:
      - min: 1
        max: 65535
  readOnlyRootFilesystem: false

---
# Role to use Pod Security Policy
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: decentralbet-psp-role
  namespace: decentralbet
rules:
- apiGroups: ['policy']
  resources: ['podsecuritypolicies']
  verbs: ['use']
  resourceNames:
  - decentralbet-psp

---
# RoleBinding for Pod Security Policy
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: decentralbet-psp-rolebinding
  namespace: decentralbet
roleRef:
  kind: Role
  name: decentralbet-psp-role
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: decentralbet-sa
  namespace: decentralbet
