name: Deploy to AKS

on:
  push:
    branches: [ develop ]
    paths: 
      - 'k8s/**'
      - 'terraform/**'
  workflow_dispatch:

env:
  RESOURCE_GROUP: decentralbet-rg
  CLUSTER_NAME: decentralbet-aks
  LOCATION: eastus

jobs:
  deploy:
    runs-on: self-hosted
    environment: production

    steps:
      - uses: actions/checkout@v4

      - name: Install tools
        run: |
          if ! command -v az &> /dev/null; then
            curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
          fi
          if ! command -v terraform &> /dev/null; then
            wget -O- https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
            echo 'deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com jammy main' | sudo tee /etc/apt/sources.list.d/hashicorp.list
            sudo apt update && sudo apt install terraform -y
          fi
          if ! command -v unzip &> /dev/null; then
            sudo apt install unzip -y
          fi
          if ! command -v kubelogin &> /dev/null; then
            curl -LO https://github.com/Azure/kubelogin/releases/download/v0.1.4/kubelogin-linux-amd64.zip
            unzip kubelogin-linux-amd64.zip
            sudo mv bin/linux_amd64/kubelogin /usr/local/bin/
            rm -rf kubelogin-linux-amd64.zip bin/
          fi

      - name: Azure login
        run: az login --identity

      - name: Check existing AKS cluster
        run: |
          if az aks show --resource-group ${{ env.RESOURCE_GROUP }} --name ${{ env.CLUSTER_NAME }} --query name -o tsv 2>/dev/null; then
            echo "AKS cluster exists, skipping terraform"
          else
            echo "AKS cluster not found, would need terraform"
            exit 1
          fi

      - name: Get AKS credentials
        run: |
          az aks get-credentials \
            --resource-group ${{ env.RESOURCE_GROUP }} \
            --name ${{ env.CLUSTER_NAME }} \
            --admin \
            --overwrite-existing

      - name: Deploy
        run: |
          kubectl apply -f k8s/
          sleep 30
          kubectl get all -n decentralbet
          if kubectl get deployment frontend -n decentralbet 2>/dev/null; then
            kubectl wait --for=condition=available --timeout=300s deployment/frontend -n decentralbet
          fi
          if kubectl get deployment backend -n decentralbet 2>/dev/null; then
            kubectl wait --for=condition=available --timeout=300s deployment/backend -n decentralbet
          fi

      - name: Status
        run: |
          kubectl get all -n decentralbet
          kubectl get services -n decentralbet
          kubectl get pods -n decentralbet
